# Jekyll configuration for Lumorik Learn
title: Lumorik Learn
description: Learn at the speed of light with AI-powered study plans
baseurl: "/learn"
url: "https://lumorikllc.github.io"

# Build settings
markdown: kramdown
theme: null

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  content:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "content"
    values:
      layout: "study-plan"