title: Lumorik Learning Hub
description: AI-Powered Study Plans and Textbooks
baseurl: "/learn"
url: "https://lumorik-ai.github.io"

# Theme and plugins
theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Exclude files from build
exclude:
  - README.md
  - LICENSE
  - .gitignore
